mainmatter/gerust

- Cargo.lock
- pacesetter-procs/Cargo.toml
- pacesetter/Cargo.toml
> update axum to 0.7

- template/.gitignore
…so there's a reasonable default
> add .gitignore to template

- blueprints/default/web/Cargo.toml
- blueprints/full/web/Cargo.toml
> remove clap and rand dependency from app crates

- Cargo.lock
- pacesetter-cli/Cargo.toml
- pacesetter-cli/src/main.rs
This bundles the blueprints with the binary (shamelessly copies what [Pavex is doing](https://github.com/LukeMathWalker/pavex/blob/18cd144ad6597efe74a10e1fdf845ece24144af8/libs/pavex_cli/src/main.rs#L213-L219)).
> Bundle blueprints

- blueprints/default/db/Cargo.toml
- blueprints/default/db/src/lib.rs
- blueprints/full/db/Cargo.toml
- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/db/src/lib.rs
- blueprints/full/web/Cargo.toml
- blueprints/full/web/src/controllers/tasks.rs
- blueprints/full/web/tests/tasks_test.rs
This also introduces the concept of a changeset that is validated – similar to what Ecte does.
> move validation into `db` crate

- blueprints/default/db/Cargo.toml
- blueprints/default/web/Cargo.toml
- blueprints/full/db/Cargo.toml
- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/db/src/test_helpers/users.rs
- blueprints/full/web/Cargo.toml
- blueprints/full/web/tests/tasks_test.rs
via the `fake` crate so we don't have to hard-code test data
> Fake data generation

- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/db/src/lib.rs
- blueprints/full/web/src/controllers/tasks.rs
- blueprints/full/web/src/routes.rs
- blueprints/full/web/tests/tasks_test.rs
> add deletion example

- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/web/src/controllers/tasks.rs
- blueprints/full/web/src/routes.rs
- blueprints/full/web/tests/tasks_test.rs
> add update example

- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/web/src/controllers/tasks.rs
- blueprints/full/web/src/routes.rs
- blueprints/full/web/tests/tasks_test.rs
…by reordering handlers in the controller so they are sorted according to CRUD (create first, then read, etc.), fixing status code, and adding missing test cases
> fix controller and controller tests in full blueprint

- pacesetter-cli/blueprints/default/config/src/lib.rs
- pacesetter-cli/blueprints/default/web/src/lib.rs
- pacesetter-cli/blueprints/full/config/src/lib.rs
- pacesetter-cli/blueprints/full/web/src/lib.rs
- pacesetter-cli/blueprints/minimal/config/src/lib.rs
- pacesetter-cli/blueprints/minimal/web/src/lib.rs
- pacesetter/Cargo.toml
- pacesetter/src/cli/db.rs
- pacesetter/src/cli/generate/mod.rs
- pacesetter/src/config.rs
- pacesetter/src/lib.rs
- pacesetter/src/test/helpers.rs
- pacesetter/src/test/mod.rs
- pacesetter/src/util.rs
- pacesetter/src/web.rs
> add API docs

- blueprint/web/tests/api/common.rs.liquid
- blueprint/web/tests/api/greeting_test.rs.liquid
- blueprint/web/tests/api/tasks_test.rs.liquid
> replace body parsing helpers with extensions on Body

- blueprint/.cargo/config.toml
- blueprint/Cargo.toml.liquid
- blueprint/cargo-generate.toml
- blueprint/cli/blueprints/controller/minimal/test.rs.liquid.liquid
- blueprint/cli/src/bin/generate.rs
…so that generators are available and behave according to whether the project includes a DB create or not
> Fix generators

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- blueprint/cargo-generate.toml
- blueprint/cli/Cargo.toml.liquid
- blueprint/cli/src/bin/generate.rs
- blueprint/config/Cargo.toml.liquid
- src/ui/mod.rs
- src/ui/snapshots/pace__ui__tests__color-2.snap
- src/ui/snapshots/pace__ui__tests__color.snap
- src/ui/snapshots/pace__ui__tests__indentation.snap
- src/ui/snapshots/pace__ui__tests__no_color-2.snap
- src/ui/snapshots/pace__ui__tests__no_color.snap
…by
* fixing the tests for the UI helper struct
* disabling doctests
* removing unused imports
> Fix cli and config crate tests

- src/main.rs
…by adding some help text and printing usage when no project name is given
> improve UX of main CLI

- renovate.json
…so we can keep those up to date as well automatically
> enable Renovate for `Cargo.toml.liquid` files in blueprints

- blueprint/macros/src/lib.rs.liquid
…since there is no DB for that project type
> don't create db_test macro for minimal project type

- blueprint/README.md
- blueprint/README.md.liquid
- blueprint/cli/README.md.liquid
- blueprint/config/README.md.liquid
- blueprint/db/README.md
- blueprint/macros/README.md.liquid
- blueprint/web/README.md.liquid
…so that the generated project itself as well as all of the individual crates have READMEs
> Add READMEs to blueprint

- blueprint/cli/src/bin/db.rs
closes #108
Duplicate, as I got some issues with commit signing
> Enable migrations to be run from any directory

- blueprint/cli/blueprints/controller/crud/controller.rs.liquid.liquid
- blueprint/cli/blueprints/controller/minimal/controller.rs.liquid.liquid
- blueprint/web/Cargo.toml.liquid
- blueprint/web/src/controllers/greeting.rs
- blueprint/web/src/controllers/tasks.rs
Docs on this macro: <https://docs.rs/axum/latest/axum/attr.debug_handler.html>
> Annotate route handlers with axum::debug_handler proc macro attribute

- blueprint/cli/blueprints/controller/crud/controller.rs.liquid.liquid
- blueprint/cli/blueprints/controller/minimal/controller.rs.liquid.liquid
- blueprint/cli/blueprints/middleware/file.rs.liquid.liquid
- blueprint/web/src/controllers/tasks.rs
- blueprint/web/src/middlewares/auth.rs
- blueprint/web/src/routes.rs.liquid
- blueprint/web/src/state.rs.liquid
> wrap the `AppState` in an `Arc`

- blueprint/config/src/lib.rs.liquid
> Config loading updates

- README.md
…which is now in the site directory
> fix path to logo

- blueprint/web/src/state.rs.liquid
- blueprint/web/tests/api/main.rs.liquid
…which breaks CI:
* remove blank line in `web/src/state.rs`
* allow missing docs for integration tests crate
> Fix format

- site/src/pages/markdown-page.md
…that was created by Docusaurus as an example
> remove example markdown page

- site/src/css/custom.css
- site/src/pages/index.tsx
> add video to landing page

- site/docusaurus.config.ts
…for better connection to Mainmatter
> add Twitter/Fed creator attribution

- site/docusaurus.config.ts
> add plausible tracking

- Cargo.toml
Resolves https://github.com/mainmatter/gerust/issues/163
> feat: Enable Link-Time Optimization (LTO)

- .github/workflows/gravity.yml
…to keep track of the size of the `.crate` file as well of the binary
> add Gravity config

- .github/workflows/gravity.yml
> Revert "Fix env secrets"

- blueprint/cli/blueprints/controller/crud/test.rs.liquid.liquid
Fixes:
* missing module name
* wrong function name
* wrong structure names
* missing ref
> fix errors in CRUD controller blueprint test

- blueprint/cli/blueprints/controller/crud/test.rs.liquid.liquid
…in the CRUD controller test blueprint
> use id property of entity var instead of own var

- .github/workflows/gravity.yml
Reverts mainmatter/gerust#225
This also doesn't work strangely…
> Revert "fix Gravity on PRs"
