mainmatter/gerust

- pacesetter/Cargo.toml
- pacesetter/src/test/helpers.rs
- template/web/src/controllers/example.rs
- template/web/src/lib.rs
- template/web/tests/example_test.rs
This improves the example test by:
* moving the helper functions to parse the response body into pacesetter
* changing the example to be JSON instead
> Improve example test

- blueprints/default/db/Cargo.toml
- blueprints/full/db/Cargo.toml
- blueprints/full/db/src/entities/mod.rs
- blueprints/full/db/src/entities/task.rs
- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/db/src/entities/user.rs
- blueprints/full/db/src/entities/users.rs
- blueprints/full/web/Cargo.toml
- blueprints/full/web/src/controllers/tasks.rs
- blueprints/full/web/src/middlewares/auth.rs
- blueprints/full/web/tests/tasks_test.rs
This moves all code (except for tests) that uses the database into the `db` crate for a cleaner architecture. That way, the `web` crate only deals with simple structs and we're not leaking all the DB complexity into it.
> Encapsulate all db access in db lib

- blueprints/full/db/Cargo.toml
- blueprints/full/db/src/lib.rs
- blueprints/full/web/src/state.rs
This moves establishing the DB connection into the `db` crate so that all DB-related code is centralized there.
> establish db connection in db crate

- Cargo.lock
- blueprints/default/db/src/lib.rs
- blueprints/default/web/Cargo.toml
- blueprints/default/web/src/state.rs
- blueprints/default/web/tests/common/mod.rs
- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/db/src/entities/users.rs
- blueprints/full/db/src/lib.rs
- blueprints/full/web/Cargo.toml
- blueprints/full/web/src/middlewares/auth.rs
- blueprints/full/web/src/state.rs
- blueprints/full/web/tests/common/mod.rs
- pacesetter/Cargo.toml
- pacesetter/src/test/helpers.rs
Since all of the DB access is encapsulated in the `db` crate, we can drop the `sqlx` dependency from the `web` crate.
> Drop sqlx dependency from web crate

- .github/workflows/ci.yml
- blueprints/default/db/src/lib.rs
- blueprints/full/db/src/entities/tasks.rs
- blueprints/full/db/src/entities/users.rs
- blueprints/full/db/src/lib.rs
- blueprints/full/web/src/controllers/tasks.rs
- blueprints/full/web/src/routes.rs
- blueprints/full/web/tests/tasks_test.rs
The helper functions in the DB crate now accept a DB pool as well as a transaction so that both of these work equally:
```rs
tasks::create(task, &app_state.db_pool).await
```
```rs
let mut transaction = app_state.db_pool.begin().await.unwrap();
tasks::create(task, &mut *transaction).await;
transaction.commit.await;
```
> introduce transactions

- blueprints/full/web/tests/tasks_test.rs
- pacesetter/src/cli/generate/blueprints/controller/crud/test.rs.liquid
- pacesetter/src/cli/generate/blueprints/controller/minimal/test.rs.liquid
Use pacesetter's test helpers for parsing responses instead of inline implementations.
> cleanup tests

- pacesetter/src/util.rs
…since to test get_env, we'd need to moficy env vars at runtime which doesn't work the way I tried in the original implementation
> test parse_env, not get_env

- Cargo.lock
- pacesetter-cli/blueprints/default/cli/Cargo.toml
- pacesetter-cli/blueprints/full/cli/Cargo.toml
- pacesetter/Cargo.toml
- pacesetter/src/lib.rs
The `pacesetter` crate is a runtime dependency of the generated project.
We need to minimise its dependency footprint to reduce compilation times, both for getting started on a project and iterating.
This PR adds a `cli` feature that gates all dependencies only required when using generators. The generated API project will therefore no longer need to compile `clap` or `liquid`.
> Add `cli` feature

- blueprint/web/tests/api/common.rs.liquid
…since that can happen if e.g. an empty app is generated fresh or the API never returns JSON.
I assume this only comes up now because of a new Clippy version on CI or so…
> don't fail if into_json of TestResponse is never used

- LICENSE.md
- README.md
> add README and LICENSE

- .github/workflows/ci.yml
…so we identify issues with dependencies early (the blueprints don't include Cargo.lock files so patch versions dependencies might change any time, potentially causing errors)
> run CI daily

- blueprint/cli/blueprints/controller/crud/controller.rs.liquid.liquid
- blueprint/cli/blueprints/controller/minimal/controller.rs.liquid.liquid
- blueprint/cli/blueprints/entity/file.rs.liquid.liquid
- blueprint/db/src/entities/tasks.rs
- blueprint/db/src/lib.rs
- blueprint/web/Cargo.toml.liquid
- blueprint/web/src/controllers/tasks.rs
- blueprint/web/src/error.rs.liquid
- blueprint/web/src/lib.rs
- Have db::Error::DbError wrap a sqlx::error instead of anyhow::Error, and clarify the semantics of db::Error::NoRecordFound
- Add error module in web crate, with Error type that implements IntoResponse. Use it in generated tasks controller
Fixes #110
> Improve error types

- blueprint/cli/src/bin/db.rs
- blueprint/cli/src/bin/generate.rs
- blueprint/web/src/routes.rs.liquid
If something goes wrong when running a command, it's always reasonable to assume the user wants error details.
> Enable error debug output by default in CLI binaries

- blueprint/cargo-generate.toml
Minimal projects should not include the file blueprints for entities and entity test helpers. Since all files end up in the user's project, that would be confusing
> Don't generate irrelevant blueprints for minimal apps

- blueprint/.cargo/config.toml
Makes `cargo generate --help` just work
> Propagate all args to cli binaries in cargo alias config

- blueprint/cli/src/bin/generate.rs
Fixes errros such as:
```
ℹ️  Migrating development database…
❌ Could not migrate database!
Failed to create migrator!
Caused by:
0: while resolving migrations: error parsing migration filename "V1732527955__test.sql"; expected integer version prefix (e.g. `01_foo.sql`)
1: error parsing migration filename "V1732527955__test.sql"; expected integer version prefix (e.g. `01_foo.sql`)
```
For migrations generated with the `cargo generate migration` command
> Remove prefix for migrations generated by the generate app

- site/docs/architecture/the-cli-crate.md
The generate CLI is pretty well-behaved and as such no elaborate instructions on where adding custom code may collide with generated code is necessary after all. 
Addresses [this comment on #130](https://github.com/mainmatter/gerust/pull/130#discussion_r1834118589)
> Describe how `generate` adds code

- Cargo.toml
…which is now `blueprint` not `blueprints`
closes #148
> fix path to blueprints dir

- blueprint/cli/src/bin/generate.rs
Currently, the `generate` cli command uses `to_title_case` to generate a struct's name. `to_title_case` results capitalized words, with spaces, not a valid Rust struct name, the correct method to use is `to_class_case`. 
```bash
cargo run -- my-app
cd my-app
cargo generate entity github_pull_requests
cat db/src/entities/github_pull_requests.rs
```
```rust
#[derive(Serialize, Debug, Deserialize)]
pub struct Github Pull Request {
// these are examples only
pub id: Uuid,
pub name: String,
}
#[derive(Deserialize, Validate, Clone)]
#[cfg_attr(feature = "test-helpers", derive(Serialize, Dummy))]
pub struct Github Pull RequestChangeset {
// these are examples only
#[cfg_attr(feature = "test-helpers", dummy(faker = "Name()"))]
#[validate(length(min = 1))]
pub name: String,
}
```
> Fix issue generating an entity with a name that's more than one word

- blueprint/macros/src/lib.rs.liquid
Hi there and thank you guys for this framework!
I needed to ignore a couple of tests and so had to patch the `macros` crate in my project.
Bringing it upstream.
We can now do the usual:
```rust
#[ignore = "no good reason"]
#[db_test]
async fn test_create_success(context: &DbTestContext) {}
#[ignore = "no good reason either"]
#[test]
async fn test_create_success(context: &DbTestContext) {}
```
To quickly test this, hit this from the project's root:
```bash
cargo run -- test_project --full
cd test_project
docker compose up -d
cargo db migrate
cargo db migrate -e test
cargo db prepare
cargo t
```
Then go ahead and ignore one of the tests in `test_project/web/tests/api/tasks_test.rs` and rerun the `cargo t` command staying in the `test_project` directory.The output  should resemble:
This …
> Make #[ignore] and other attrs on tests possible

- blueprint/cli/blueprints/controller/crud/test.rs.liquid.liquid
- blueprint/cli/blueprints/controller/minimal/test.rs.liquid.liquid
- blueprint/cli/src/bin/db.rs
- blueprint/cli/src/bin/generate.rs
- blueprint/web/src/main.rs
- src/main.rs
- src/ui/mod.rs
This fixes the exit codes of the project binaries that currently swallow any errors (they log the errors but always return a successful exit code. That's not critical when working with the binaries in development but leads to bugs like #169 going unnoticed in CI…
The code is quite repetitive now and could use some cleanup eventually.
This also fixes 2 actual errors in the generators which fix CI (which now correctly fails because of these errors).
closes #169
> fix exit codes of binaries

- .github/workflows/gravity.yml
…so Gravity doesn't fail on jobs triggered from a PR from a fork, e.g. #190
> Fix env secrets

- .github/workflows/gravity.yml
Since builds on forks don't receive secrets, the Gravity job can never work, see e.g. #190
> do nor tun Gravtiy on forks

- blueprint/cli/blueprints/controller/crud/test.rs.liquid.liquid
The name of the example attribute in the `entity` blueprint is `name` but in the blueprint for the CRUD controller test we're using `description` which is confusing
> Rename `description` attribute to `name` in CRUD controller test blueprint

- blueprint/cli/src/bin/db.rs
No functional changes. 
Remove unnecessary reference that is immediately dereferenced (``clippy::needless_borrow``).
Thank you for your work!
> refactor(cli): Remove needless borrow

- blueprint/cli/src/bin/db.rs
The transaction was never committed so the seeds were never actually applied to the db…
closes #212
> Fix seeding task

- .github/workflows/release.yml
I should probably use release-plz at some point but for now this is good enough
> release tags automatically to crates.io

- .github/workflows/gravity.yml
…by preventing it from running at all. Gravity cannot run in PRs since those don't have access to secrets (see e.g. #224).
> fix Gravity on PRs

- .github/workflows/ci.yml
- blueprint/cli/Cargo.toml.liquid
- blueprint/cli/blueprints/entity/file.rs.liquid.liquid
- blueprint/cli/src/bin/generate.rs
- site/docs/tutorial-standard/auth-middleware.md
- site/docs/tutorial-standard/reading-endpoints.md
- site/docs/tutorial-standard/the-entity.md
…so not everyone needs to always change the field names and adopt all SQL quieries
```
cargo generate entity Person first_name:String last_name:String age:i16
```
> Allow field names to be specified when generating an entity

- README.md
- blueprint/cli/src/bin/generate.rs
- site/docs/architecture/the-cli-crate.md
Currently, `cargo generate` will just happily override any existing files which of course might override changes the developer has made already. This fixes changes the behavior so that if the generator finds that a file already exists, it fails with an error.
> don't just override project files
